language: node_js
sudo: true
node_js:
- "8.11.2"

git:
  submodules: false

script:
- npm run-script test-travis

deploy:
  provider: npm
  email: vyacheslav.chub@valor-software.com
  api_key:
    secure: $GITHUB_TOKEN
  on:
    branch: develop
    node: 8.11.2
    condition: "-e /tmp/deployment.flag"

branches:
  only:
  - master
  - development
